version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10

    working_directory: ~/middy

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: configure NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: install lerna
          command: sudo npm i -g lerna

      - run:
          name: lerna bootstrap
          command: lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: npm test

      # - run:
      #     name: coverage reporting
      #     command: npm run coverage:submit

      - deploy:
          name: publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "1.0.0-alpha" ]; then
              npm run lerna:publish && npm run release:tag;
            fi
